# Generated by Django 5.2.11 on 2026-02-04 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErpSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(help_text='Raw ERP data including Sales, Warehouse, Finance, CRM')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleaning_analysis', models.JSONField(default=dict, help_text='Data quality analysis and red flags')),
                ('business_strategy', models.JSONField(default=dict, help_text='Top 5 problems, root causes, and actions')),
                ('erp_actions', models.JSONField(default=dict, help_text='Specific Bito ERP module configuration changes')),
                ('erp_snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.erpsnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
