# Generated by Codex on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
